# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 9200, host: 9200

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "./cookbooks/Berksfile"

  config.vm.provision "chef_solo" do |chef|
	  chef.add_recipe "sw-elasticsearch::default"
  end
end
